[16:07:50] [ClientServer/ClientMain/KERNEL]: 1.开始建立网络连接…………
[16:07:50] [ClientServer/ClientMain/KERNEL]: 2.网络连接成功！启动loginBox
[16:07:51] [ClientServer/ClientMain/KERNEL]: 2.同时发送0000包，确认对方是否为网关
[16:07:51] [AioModule/Write/Completed/DEBUG]: Sent 14 bytes to session/162.105.38.69:8438
[16:07:51] [AioModule/Write/Completed/DEBUG]: Sent contents(14bytes): ff ff 00 00 00 0e 00 00 00 00 30 39 20 db 
[16:07:51] [AioModule/Read/Completed/DEBUG]: Received 11 bytes from session/162.105.38.69:8438
[16:07:51] [AioModule/Read/Completed/DEBUG]: Received contents(11bytes): ff ff 00 00 00 0b 00 01 01 2a 46 
[16:07:51] [ClientServer/ClientDecoder/INFO]: Receive a package 0001(回应连接请求)
[16:07:51] [ClientServer/ClientDecoder/INFO]: package 0001: 1
[16:07:51] [ClientSever/LoginBox/serverState/INFO]: Receive a package 0001(回应连接请求)
[16:07:51] [ClientSever/LoginBox/serverState/INFO]: package 0001: 1
[16:07:55] [ClientServer/ClientMain/KERNEL]: 3.登陆结束
[16:07:55] [ClientServer/ClientMain/KERNEL]: 登陆失败，退出主程序
[16:08:28] [AioModule/Read/Failed/WARNING]: Failed to read from session/162.105.38.69:8438. java.io.IOException: 指定的网络名不再可用。

